### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by alalaha** [ChrisDiep/Leek-Bot#14]
Hi, first you did an excellent job here.
I would like help or at least a tip to self host your bot, it would help me and my friends.

**Comment by ChrisDiep** [comment]
Hi! I really appreciate the interest. Feel free to self-host the bot if you would like. I'm fairly busy right now, but if you email me I can get back to you with help self-hosting the bot if you need it. I also plan on adding multi-server support sometime in the future, so I can also notify you when that feature is out!

**Comment by alalaha** [comment]
> Hi! I really appreciate the interest. Feel free to self-host the bot if you would like. I'm fairly busy right now, but if you email me I can get back to you with help self-hosting the bot if you need it. I also plan on adding multi-server support sometime in the future, so I can also notify you when that feature is out!

Hi, I contacted you by email.
Is your email "ChrisLDiep@gmail.com"?

**Comment by ChrisDiep** [comment]
Continued conversation on e-mail
